version: '3.8'

services:
  php:
    image: php:8.2-fpm
    container_name: php-fpm
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:80
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-database
    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  dbdata:
    driver: local
  moodle_dbdata:
    driver: local